[general]
import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[font]
size = 10

[font.bold]
family = "MonaspiceNe Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspiceNe Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonaspiceNe Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[env]
TERM = "xterm-256color"
